@startuml
'https://plantuml.com/class-diagram

class HitboxComponent {
    Rectangle[] rects
    Rectangle region
}

class FixtureComponent {
    Fixture fixture
}

class PlayerComponent {
    boolean isInteracting
}

class InteractionComponent{
    Interactable interactable
}

Player *-- FixtureComponent
Player *-- PlayerComponent
Interactable *-- HitboxComponent
Interactable *-- InteractionComponent


@enduml