@startuml
'https://plantuml.com/class-diagram

class HitboxComponent {
    Rectangle[] rects
    Rectangle region
}

class FixtureComponent {
    Fixture fixture
}

class TooltipComponent {
    GlyphLayout tooltip
}

Player *-- FixtureComponent
Interactable *-- TooltipComponent
Interactable *-- HitboxComponent


@enduml