on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Check format
        run: ./gradlew spotlessCheck
      - name: Test
        run: ./gradlew clean tests:test
      - name: Build
        run: ./gradlew build jacocoTestReport
      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v4.3.1
        with:
          name: jacoco-report-${{ ubuntu-latest }}
          path: tests/build/reports/jacoco/test/html/
      - name: Upload JAR
        uses: actions/upload-artifact@v4.3.1
        with:
          name: lib-${{ ubuntu-latest }}.jar
          path: tests/build/libs/lib.jar
